# Spectral configuration for OpenAPI contract validation
# This file is used for all OpenAPI specs in this project
# Location: project root (/docs/education/API_contracts/)
# Usage: spectral lint <path-to-yaml>

extends: ["spectral:oas"]

rules:
  # OpenAPI Rules
  info-contact: warn
  info-description: warn
  info-license: off  # Not required for educational examples
  license-url: off

  # Require operation IDs (important for code generation)
  operation-operationId: error
  operation-operationId-unique: error

  # Require descriptions for better documentation
  operation-description: warn

  # Require tags for organization
  operation-tags: warn
  operation-tag-defined: error

  # Schema best practices
  oas3-schema: error
  oas3-valid-media-example: warn
  oas3-valid-schema-example: warn

  # Parameter rules
  operation-parameters: warn
  path-params: error

  # Response rules
  operation-success-response: error
  no-$ref-siblings: error

  # Security
  oas3-api-servers: warn

  # Path rules
  path-declarations-must-exist: error
  path-keys-no-trailing-slash: error
  path-not-include-query: error