/**
 * Site Map Generation API Client
 */

export interface GenerationRequest {
  camera_ids: string[]
  cameras_data: CameraData[]
  capture_method?: 'vapix' | 'rtsp'
}

export interface CameraData {
  id: string
  position: {
    x: number
    y: number
    z: number
    azimuth: number
    elevation: number
  }
  capabilities: {
    resolution: string
    fps: number
  }
  ipAddress?: string
  rtspUrl?: string
}

export interface GenerationProgress {
  status: 'pending' | 'processing' | 'completed' | 'failed'
  current_camera?: string
  cameras_processed: number
  total_cameras: number
  message: string
}

export interface GenerationResponse {
  generation_id: string
  status: string
  site_map_path?: string
  site_map_data?: GeneratedSiteMap
  error?: string
}

export interface GeneratedSiteMap {
  id: string
  name: string
  description: string
  generated_at: string
  cameras_used: string[]
  width: number
  height: number
  scale: number
  origin: {
    x: number
    y: number
  }
  walls: GeneratedWall[]
  fog_of_war_regions: FogOfWarRegion[]
  cameras: CameraPlacement[]
  createdAt: string
  updatedAt: string
}

export interface GeneratedWall {
  id: string
  start: { x: number; y: number }
  end: { x: number; y: number }
  type: string
  confidence: number
  source: string
}

export interface FogOfWarRegion {
  polygon: Array<{ x: number; y: number }>
  assumed_type: string
  confidence: number
  area_m2: number
}

export interface CameraPlacement {
  cameraId: string
  x: number
  y: number
  rotation: number
  angle: number
  height: number
  fov: number
  viewDistance: number
  autoCalculateDistance: boolean
  color: string
}

const API_BASE_URL = 'http://localhost:8091'

export class SiteMapGenerationClient {
  private baseUrl: string

  constructor(baseUrl: string = API_BASE_URL) {
    this.baseUrl = baseUrl
  }

  /**
   * Start site map generation
   */
  async startGeneration(request: GenerationRequest): Promise<GenerationResponse> {
    const response = await fetch(`${this.baseUrl}/api/generate`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(request),
    })

    if (!response.ok) {
      throw new Error(`Generation request failed: ${response.statusText}`)
    }

    return response.json()
  }

  /**
   * Get generation status
   */
  async getGenerationStatus(generationId: string): Promise<GenerationResponse> {
    const response = await fetch(`${this.baseUrl}/api/generate/${generationId}`)

    if (!response.ok) {
      throw new Error(`Failed to get generation status: ${response.statusText}`)
    }

    return response.json()
  }

  /**
   * Poll generation status until completed or failed
   */
  async pollGenerationStatus(
    generationId: string,
    onProgress?: (progress: GenerationResponse) => void,
    pollInterval: number = 1000
  ): Promise<GeneratedSiteMap> {
    return new Promise((resolve, reject) => {
      const poll = async () => {
        try {
          const response = await this.getGenerationStatus(generationId)

          // Call progress callback
          if (onProgress) {
            onProgress(response)
          }

          // Check status
          if (response.status === 'completed' && response.site_map_data) {
            resolve(response.site_map_data)
          } else if (response.status === 'failed') {
            reject(new Error(response.error || 'Generation failed'))
          } else {
            // Continue polling
            setTimeout(poll, pollInterval)
          }
        } catch (error) {
          reject(error)
        }
      }

      // Start polling
      poll()
    })
  }

  /**
   * Health check
   */
  async healthCheck(): Promise<{ status: string }> {
    const response = await fetch(`${this.baseUrl}/health`)

    if (!response.ok) {
      throw new Error('Health check failed')
    }

    return response.json()
  }

  /**
   * Load generated site map from static file
   * This loads the sitemap-setup.json file generated by `make sitemap`
   */
  async loadGeneratedSiteMap(): Promise<GeneratedSiteMap> {
    const response = await fetch('/shared/site-maps/generated/sitemap-setup.json')

    if (!response.ok) {
      throw new Error('Site map file not found. Please run "make sitemap" to generate it.')
    }

    return response.json()
  }
}

// Export singleton instance
export const siteMapClient = new SiteMapGenerationClient()
