# Camera Configuration for Axis-Guardian Simulation
# This file defines all simulated cameras and their properties

cameras:
  - id: camera1
    name: "Auditorium - High Corner View 3"
    description: "Auditorium monitoring - high corner camera position 3"

    # Video sources
    source_video: "view-HC3.mp4"
    rendered_video: "view-HC3-rendered.mp4"
    detections_json: "view-HC3-rendered.detections.json"

    # Stream configuration
    rtsp_url: "rtsp://localhost:8554/camera1"
    resolution: "1920x1080"
    fps: 30
    bitrate: "4M"

    # Camera capabilities
    capabilities:
      - object_detection
      - people_counting
      - motion_detection

    # Detection classes this camera focuses on
    detection_classes:
      - person
      - chair
      - backpack

    # VAPIX properties
    vapix:
      brand: "AXIS"
      model: "P3245-LVE"
      serial_number: "ACCC8E123460"
      firmware_version: "11.8.67"
      mac_address: "AC:CC:8E:12:34:60"

    # Physical location
    location:
      site: "Auditorium"
      zone: "Main Hall"
      coordinates:
        x: 50
        y: 50
        z: 5.0

  - id: camera2
    name: "Auditorium - High Corner View 4"
    description: "Auditorium monitoring - high corner camera position 4"

    # Video sources
    source_video: "view-HC4.mp4"
    rendered_video: "view-HC4-rendered.mp4"
    detections_json: "view-HC4-rendered.detections.json"

    # Stream configuration
    rtsp_url: "rtsp://localhost:8554/camera2"
    resolution: "1920x1080"
    fps: 30
    bitrate: "4M"

    # Camera capabilities
    capabilities:
      - object_detection
      - people_counting
      - motion_detection

    # Detection classes this camera focuses on
    detection_classes:
      - person
      - chair
      - backpack

    # VAPIX properties
    vapix:
      brand: "AXIS"
      model: "P3245-LVE"
      serial_number: "ACCC8E123461"
      firmware_version: "11.8.67"
      mac_address: "AC:CC:8E:12:34:61"

    # Physical location
    location:
      site: "Auditorium"
      zone: "Main Hall"
      coordinates:
        x: 150
        y: 50
        z: 5.0

  - id: camera3
    name: "Auditorium - IP Camera View 2"
    description: "Auditorium monitoring - IP camera position 2"

    # Video sources
    source_video: "view-IP2.mp4"
    rendered_video: "view-IP2-rendered.mp4"
    detections_json: "view-IP2-rendered.detections.json"

    # Stream configuration
    rtsp_url: "rtsp://localhost:8554/camera3"
    resolution: "1920x1080"
    fps: 30
    bitrate: "4M"

    # Camera capabilities
    capabilities:
      - object_detection
      - people_counting
      - motion_detection

    # Detection classes this camera focuses on
    detection_classes:
      - person
      - chair
      - backpack

    # VAPIX properties
    vapix:
      brand: "AXIS"
      model: "P3245-LVE"
      serial_number: "ACCC8E123462"
      firmware_version: "11.8.67"
      mac_address: "AC:CC:8E:12:34:62"

    # Physical location
    location:
      site: "Auditorium"
      zone: "Main Hall"
      coordinates:
        x: 100
        y: 100
        z: 3.0

  - id: camera4
    name: "Auditorium - IP Camera View 5"
    description: "Auditorium monitoring - IP camera position 5"

    # Video sources
    source_video: "view-IP5.mp4"
    rendered_video: "view-IP5-rendered.mp4"
    detections_json: "view-IP5-rendered.detections.json"

    # Stream configuration
    rtsp_url: "rtsp://localhost:8554/camera4"
    resolution: "1920x1080"
    fps: 30
    bitrate: "4M"

    # Camera capabilities
    capabilities:
      - object_detection
      - people_counting
      - motion_detection

    # Detection classes this camera focuses on
    detection_classes:
      - person
      - chair
      - backpack

    # VAPIX properties
    vapix:
      brand: "AXIS"
      model: "P3245-LVE"
      serial_number: "ACCC8E123463"
      firmware_version: "11.8.67"
      mac_address: "AC:CC:8E:12:34:63"

    # Physical location
    location:
      site: "Auditorium"
      zone: "Main Hall"
      coordinates:
        x: 100
        y: 150
        z: 3.0

# Global detection settings (can be overridden per camera)
detection_defaults:
  confidence_threshold: 0.5
  iou_threshold: 0.45
  model: "yolov8n.pt"
  inference_resolution: 640
  frame_skip: 1
  max_fps: 30
  auto_scale: true

# Video path configuration
paths:
  cameras_dir: "shared/cameras"
  rendered_dir: "shared/cameras/rendered"
  models_dir: "shared/models"
