extends: ["spectral:oas"]
rules:
  # Custom rules for our API standards
  info-contact: false  # Don't require contact info for internal APIs
  info-description: true
  operation-description: false  # Don't require description for every operation
  operation-operationId: true
  operation-tags: false  # Don't require tags for every operation
  no-$ref-siblings: true
  typed-enum: true
  oas3-unused-component: true

  # Custom naming conventions
  operation-operationId-valid-in-url:
    description: "Operation IDs must be URL-safe"
    given: "$.paths.*[get,put,post,delete,options,head,patch,trace]"
    then:
      field: "operationId"
      function: "pattern"
      functionOptions:
        match: "^[a-zA-Z][a-zA-Z0-9_]*$"

  # Ensure consistent error responses
  error-response-schema:
    description: "All error responses should use ErrorResponse schema"
    given: "$.paths.*.*.responses[?(@property >= '400')]"
    then:
      field: "content.application/json.schema.$ref"
      function: "pattern"
      functionOptions:
        match: ".*ErrorResponse$"
    severity: "warn"