openapi: 3.0.3
info:
  title: Camera Models
  version: 1.0.0
  description: Camera-related data models

components:
  schemas:
    Camera:
      type: object
      required:
        - id
        - name
        - status
      properties:
        id:
          type: string
          description: Unique camera identifier
          example: "cam-001"
        name:
          type: string
          description: Camera display name
          example: "Front Entrance"
        location:
          type: string
          description: Physical location
          example: "Building A"
        status:
          $ref: '#/components/schemas/CameraStatus'

    CameraCreate:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
          example: "New Camera"
        location:
          type: string
          maxLength: 200
          example: "Building B"

    CameraStatus:
      type: string
      enum:
        - online
        - offline
      description: Camera operational status
      example: "online"