openapi: 3.0.3
info:
  title: Common Schemas
  version: 1.0.0
  description: Shared data types used across all APIs

components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Error code
          example: "NOT_FOUND"
        message:
          type: string
          description: Human-readable error message
          example: "Resource not found"