services:
  camera-emulator:
    build: .
    container_name: axis-camera-emulator
    network_mode: host
    volumes:
      - ../../shared:/shared:ro
    environment:
      - CAMERA_DATA_PATH=/shared/cameras/preprocessed/1080p
      - LOG_LEVEL=INFO
    restart: unless-stopped
